In [25]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
import sys
print(sys.version)



3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]


In [45]:
!pip install tensorflow

In [2]:
pip show tensorflow


Name: tensorflow
Version: 2.12.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\iftekar\anaconda3\lib\site-packages
Requires: tensorflow-intel
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
X = dataset.drop('Exited',axis=1)
y = dataset['Exited']

In [6]:
X

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
X['Gender'] = le.fit_transform(X['Gender'])

In [10]:
X

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France       0   42   
1             2    15647311       Hill          608     Spain       0   41   
2             3    15619304       Onio          502    France       0   42   
3             4    15701354       Boni          699    France       0   39   
4             5    15737888   Mitchell          850     Spain       0   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France       1   39   
9996       9997    15569892  Johnstone          516    France       1   35   
9997       9998    15584532        Liu          709    France       0   36   
9998       9999    15682355  Sabbatini          772   Germany       1   42   
9999      10000    15628319     Walker          792    France       0   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  
0           101348.88  
1           112542.58  
2           113931.57  
3            93826.63  
4            79084.10  
...               ...  
9995         96270.64  
9996        101699.77  
9997         42085.58  
9998         92888.52  
9999         38190.78  

[10000 rows x 13 columns]

In [11]:
pd.get_dummies(X['Geography'])

France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [12]:
X = pd.concat([X,pd.get_dummies(X['Geography'])],axis = 1 )

In [13]:
X.drop('Geography',axis = 1,inplace=True)

In [14]:
X = X.drop(['RowNumber','CustomerId','Surname'],axis = 1)

In [15]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germany  Spain  
0                  1        101348.88       1        0      0  
1                  1        112542.58       0        0      1  
2                  0        113931.57       1        0      0  
3                  0         93826.63       1        0      0  
4                  1         79084.10       0        0      1  
...              ...              ...     ...      ...    ...  
9995               0         96270.64       1        0      0  
9996               1        101699.77       1        0      0  
9997               1         42085.58       1        0      0  
9998               0         92888.52       0        1      0  
9999               0         38190.78       1        0      0  

[10000 rows x 12 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size= 0.2,random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
X_train = sc.fit_transform(X_train)

In [21]:
X_train[0]

array([ 0.35649971,  0.91324755, -0.6557859 ,  0.34567966, -1.21847056,
        0.80843615,  0.64920267,  0.97481699,  1.36766974,  1.00150113,
       -0.57946723, -0.57638802])

In [22]:
X_test = sc.transform(X_test)

In [23]:
!pip install keras

In [24]:
from tensorflow import keras

ImportError: cannot import name 'keras' from 'tensorflow' (unknown location)

In [27]:
ann = tf.keras.models.Sequential() #Initializing the ANN

AttributeError: module 'tensorflow' has no attribute 'keras'

In [99]:
#Adding the input layer and the first hidden layer

In [100]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [101]:
#Adding the output layer

In [102]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [103]:
# Compiling the ANN

In [104]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [105]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5785 - accuracy: 0.7369
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4807 - accuracy: 0.7976
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4525 - accuracy: 0.8021
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4407 - accuracy: 0.8069
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4326 - accuracy: 0.8090
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4251 - accuracy: 0.8164
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4173 - accuracy: 0.8186
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4094 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4018 - accuracy: 0.8274
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3949 - accura

In [34]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  France  Germany  Spain  
0                  1        101348.88       1        0      0  
1                  1        112542.58       0        0      1  
2                  0        113931.57       1        0      0  
3                  0         93826.63       1        0      0  
4                  1         79084.10       0        0      1  
...              ...              ...     ...      ...    ...  
9995               0         96270.64       1        0      0  
9996               1        101699.77       1        0      0  
9997               1         42085.58       1        0      0  
9998               0         92888.52       0        1      0  
9999               0         38190.78       1        0      0  

[10000 rows x 12 columns]

In [106]:
print(ann.predict(sc.transform([[600, 1, 40, 3, 60000, 2, 1, 1, 50000,1 ,0 ,0]]))> 0.5)

C:\Users\Iftekar\anaconda3\envs\artifical\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


1/1 [==============================] - 0s 60ms/step
[[False]]


In [107]:
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 917us/step


In [108]:
y_pred

array([[0.0404644 ],
       [0.01927587],
       [0.12578766],
       ...,
       [0.652534  ],
       [0.0863076 ],
       [0.3209688 ]], dtype=float32)

In [109]:
y_pred = (y_pred > 0.5)

In [110]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1539   68]
 [ 212  181]]


0.86

In [111]:
y_pred_train = ann.predict(X_train)
y_pred_train

250/250 [==============================] - 0s 1ms/step


array([[0.00451138],
       [0.06692685],
       [0.03582785],
       ...,
       [0.7770925 ],
       [0.24924661],
       [0.5853244 ]], dtype=float32)

In [112]:
y_pred_train = (y_pred_train > 0.5)

In [113]:
accuracy_score(y_train, y_pred_train)

0.863375