In [ ]:
import requests

# URL for the plain text version of Moby Dick
url = "https://www.gutenberg.org/files/2701/2701-0.txt"

# Download the text
response = requests.get(url)
moby_dick_text = response.text

# Save it to a local file
with open("moby_dick.txt", "w", encoding="utf-8") as f:
    f.write(moby_dick_text)


In [ ]:
print(moby_dick_text)

*** START OF THE PROJECT GUTENBERG EBOOK 2701 ***




MOBY-DICK;

or, THE WHALE.

By Herman Melville



CONTENTS

ETYMOLOGY.

EXTRACTS (Supplied by a Sub-Sub-Librarian).

CHAPTER 1. Loomings.

CHAPTER 2. The Carpet-Bag.

CHAPTER 3. The Spouter-Inn.

CHAPTER 4. The Counterpane.

CHAPTER 5. Breakfast.

CHAPTER 6. The Street.

CHAPTER 7. The Chapel.

CHAPTER 8. The Pulpit.

CHAPTER 9. The Sermon.

CHAPTER 10. A Bosom Friend.

CHAPTER 11. Nightgown.

CHAPTER 12. Biographical.

CHAPTER 13. Wheelbarrow.

CHAPTER 14. Nantucket.

CHAPTER 15. Chowder.

CHAPTER 16. The Ship.

CHAPTER 17. The Ramadan.

CHAPTER 18. His Mark.

CHAPTER 19. The Prophet.

CHAPTER 20. All Astir.

CHAPTER 21. Going Aboard.

CHAPTER 22. Merry Christmas.

CHAPTER 23. The Lee Shore.

CHAPTER 24. The Advocate.

CHAPTER 25. Postscript.

CHAPTER 26. Knights and Squires.

CHAPTER 27. Knights and Squires.

CHAPTER 28. Ahab.

CHAPTER 29. Enter Ahab; to Him, Stubb.

CHAPTER 30. The Pipe.

CHAPTER 31. Queen Mab.

CHAPTER 32. Cetol

In [ ]:
# Read the uploaded file and extract lines 1 to 1868
file_path = "/content/moby_dick.txt"
output_path = "/content/moby_dick_e.txt"

# Read the file and extract the required lines
with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Extract lines from 1 to 1868
extracted_content = "".join(lines[:1868])

# Save the extracted content to a new file
with open(output_path, "w", encoding="utf-8") as f:
    f.write(extracted_content)

# Return the path of the saved file
output_path


'/content/moby_dick_e.txt'

In [ ]:
# Function to read a file and return it as a single string of that particular document
def read_file(file_path):
    with open(file_path) as f:
         str_text = f.read()
    return str_text

In [ ]:

# Load the text
file_path = "/content/moby_dick_e.txt"
text = read_file(file_path)

# Check the first few lines
print(text)

*** START OF THE PROJECT GUTENBERG EBOOK 2701 ***




MOBY-DICK;

or, THE WHALE.

By Herman Melville



CONTENTS

ETYMOLOGY.

EXTRACTS (Supplied by a Sub-Sub-Librarian).

CHAPTER 1. Loomings.

CHAPTER 2. The Carpet-Bag.

CHAPTER 3. The Spouter-Inn.

CHAPTER 4. The Counterpane.

CHAPTER 5. Breakfast.

CHAPTER 6. The Street.

CHAPTER 7. The Chapel.

CHAPTER 8. The Pulpit.

CHAPTER 9. The Sermon.

CHAPTER 10. A Bosom Friend.

CHAPTER 11. Nightgown.

CHAPTER 12. Biographical.

CHAPTER 13. Wheelbarrow.

CHAPTER 14. Nantucket.

CHAPTER 15. Chowder.

CHAPTER 16. The Ship.

CHAPTER 17. The Ramadan.

CHAPTER 18. His Mark.

CHAPTER 19. The Prophet.

CHAPTER 20. All Astir.

CHAPTER 21. Going Aboard.

CHAPTER 22. Merry Christmas.

CHAPTER 23. The Lee Shore.

CHAPTER 24. The Advocate.

CHAPTER 25. Postscript.

CHAPTER 26. Knights and Squires.

CHAPTER 27. Knights and Squires.

CHAPTER 28. Ahab.

CHAPTER 29. Enter Ahab; to Him, Stubb.

CHAPTER 30. The Pipe.

CHAPTER 31. Queen Mab.

CHAPTER 32. Cetol

In [ ]:
import spacy

# Load SpaCy tokenizer (disable unnecessary components for speed)
nlp = spacy.load("en_core_web_sm", disable=["parser", "tagger", "ner"])
nlp.max_length = 1198623  # Adjust max length if needed

In [ ]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [ ]:

tokens = separate_punc(text)

/usr/local/lib/python3.11/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [ ]:
print("Sample Tokens:", tokens[:50])  # Preview first 50 tokens

Sample Tokens: ['start', 'of', 'the', 'project', 'gutenberg', 'ebook', '2701', '\n\n\n\n\n', 'moby', 'dick', 'or', 'the', 'whale', 'by', 'herman', 'melville', '\n\n\n\n', 'contents', 'etymology', 'extracts', 'supplied', 'by', 'a', 'sub', 'sub', 'librarian', 'chapter', '1', 'loomings', 'chapter', '2', 'the', 'carpet', 'bag', 'chapter', '3', 'the', 'spouter', 'inn', 'chapter', '4', 'the', 'counterpane', 'chapter', '5', 'breakfast', 'chapter', '6', 'the', 'street']


In [ ]:
def clean_tokens(tokens):
    """
    Removes unwanted sections like Project Gutenberg text, chapter titles, and numbers.
    """
    # Find the start of Chapter 1 content
    try:
        start_index = tokens.index("loomings")  # Find where 'Loomings' appears
    except ValueError:
        print("❌ 'Loomings' not found. Check tokenization.")
        return []

    # Remove all content before 'Loomings' (start of the book)
    tokens = tokens[start_index:]

    # Remove "chapter" occurrences and numbers (e.g., "chapter 2", "3", etc.)
    tokens = [word for word in tokens if word not in ["chapter"] and not word.isdigit()]

    return tokens

# Apply the cleaning function
cleaned_tokens = clean_tokens(tokens)

print("✅ Cleaned Sample Tokens:", cleaned_tokens[:50])  # Preview first 50 cleaned tokens


✅ Cleaned Sample Tokens: ['loomings', 'the', 'carpet', 'bag', 'the', 'spouter', 'inn', 'the', 'counterpane', 'breakfast', 'the', 'street', 'the', 'chapel', 'the', 'pulpit', 'the', 'sermon', 'a', 'bosom', 'friend', 'nightgown', 'biographical', 'wheelbarrow', 'nantucket', 'chowder', 'the', 'ship', 'the', 'ramadan', 'his', 'mark', 'the', 'prophet', 'all', 'astir', 'going', 'aboard', 'merry', 'christmas', 'the', 'lee', 'shore', 'the', 'advocate', 'postscript', 'knights', 'and', 'squires', 'knights']


In [ ]:
# Define sequence length (25 input + 1 target)
train_len = 25 + 1

# Create sequences
text_sequences = []

for i in range(train_len, len(cleaned_tokens)):
    seq = cleaned_tokens[i - train_len:i]  # Extract sequence
    text_sequences.append(seq)

# Print a sample sequence
print("✅ Sample Sequence:", text_sequences[0])


✅ Sample Sequence: ['loomings', 'the', 'carpet', 'bag', 'the', 'spouter', 'inn', 'the', 'counterpane', 'breakfast', 'the', 'street', 'the', 'chapel', 'the', 'pulpit', 'the', 'sermon', 'a', 'bosom', 'friend', 'nightgown', 'biographical', 'wheelbarrow', 'nantucket', 'chowder']


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
#from keras.preprocessing.text import Tokenizer

# Initialize tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)

# Convert text sequences into numerical sequences
sequences = tokenizer.texts_to_sequences(text_sequences)

# Check vocabulary size
vocabulary_size = len(tokenizer.word_counts) + 1  # +1 because indexing starts from 1
print("📌 Vocabulary Size:", vocabulary_size)

# Print a sample numerical sequence
print("✅ Sample Encoded Sequence:", sequences[0])


📌 Vocabulary Size: 3703
✅ Sample Encoded Sequence: [1314, 1, 767, 222, 1, 418, 417, 1, 340, 3701, 1, 339, 1, 1311, 1, 1309, 1, 3700, 2, 3699, 3697, 3695, 3694, 3693, 136, 1315]


In [ ]:
print(sequences[0]) # View first sequence
print(tokenizer.index_word) # View the dictionary which contains token to index details

[1314, 1, 767, 222, 1, 418, 417, 1, 340, 3701, 1, 339, 1, 1311, 1, 1309, 1, 3700, 2, 3699, 3697, 3695, 3694, 3693, 136, 1315]
{1: 'the', 2: 'a', 3: 'and', 4: 'of', 5: 'to', 6: 'in', 7: 'i', 8: '\n  ', 9: 'it', 10: '—', 11: 'that', 12: '“', 13: '”', 14: 'his', 15: 'he', 16: '’s', 17: 'was', 18: 'with', 19: 'but', 20: 'as', 21: 'is', 22: 'at', 23: 'me', 24: 'whale', 25: 'this', 26: 'for', 27: 'you', 28: 'on', 29: 'all', 30: 'be', 31: 'from', 32: 'my', 33: 'there', 34: 'not', 35: 'one', 36: '\n\n  ', 37: 'by', 38: 'up', 39: 'or', 40: 'him', 41: 'so', 42: 'what', 43: 'out', 44: 'now', 45: 'have', 46: 'they', 47: 'which', 48: 'had', 49: 'no', 50: 'into', 51: 'were', 52: 'about', 53: 'bed', 54: 'some', 55: 'sea', 56: 'an', 57: 'like', 58: 'then', 59: 'upon', 60: 'harpooneer', 61: 'head', 62: 'over', 63: 'if', 64: 'old', 65: 'would', 66: 'little', 67: 'their', 68: 'when', 69: 'great', 70: 'whales', 71: 'are', 72: 'could', 73: 'these', 74: 'do', 75: 'first', 76: 'night', 77: 'here', 78: 'thoug

In [ ]:
# to view the index to token matching of the first sequence
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

1314 : loomings
1 : the
767 : carpet
222 : bag
1 : the
418 : spouter
417 : inn
1 : the
340 : counterpane
3701 : breakfast
1 : the
339 : street
1 : the
1311 : chapel
1 : the
1309 : pulpit
1 : the
3700 : sermon
2 : a
3699 : bosom
3697 : friend
3695 : nightgown
3694 : biographical
3693 : wheelbarrow
136 : nantucket
1315 : chowder


In [ ]:
# Check word frequencies
word_counts = tokenizer.word_counts

# Get vocabulary size (total unique words)
vocabulary_size = len(word_counts) + 1  # +1 because Keras indexing starts from 1

print("📌 Vocabulary Size:", vocabulary_size)


📌 Vocabulary Size: 3703


In [ ]:
print(word_counts)

OrderedDict([('loomings', 27), ('the', 24841), ('carpet', 55), ('bag', 212), ('spouter', 110), ('inn', 111), ('counterpane', 139), ('breakfast', 10), ('street', 142), ('chapel', 40), ('pulpit', 42), ('sermon', 18), ('a', 13048), ('bosom', 20), ('friend', 21), ('nightgown', 22), ('biographical', 23), ('wheelbarrow', 24), ('nantucket', 415), ('chowder', 26), ('ship', 442), ('ramadan', 26), ('his', 4101), ('mark', 52), ('prophet', 52), ('all', 2184), ('astir', 26), ('going', 286), ('aboard', 52), ('merry', 26), ('christmas', 26), ('lee', 78), ('shore', 130), ('advocate', 26), ('postscript', 26), ('knights', 52), ('and', 12824), ('squires', 52), ('ahab', 156), ('enter', 104), ('to', 8788), ('him', 1378), ('stubb', 104), ('pipe', 130), ('queen', 78), ('mab', 26), ('cetology', 52), ('specksnyder', 26), ('cabin', 78), ('table', 182), ('mast', 208), ('head', 884), ('quarter', 78), ('deck', 130), ('sunset', 52), ('dusk', 26), ('first', 702), ('night', 702), ('watch', 156), ('midnight', 104), ('

In [ ]:
import numpy as np

# Convert list of sequences to a NumPy array
sequences = np.array(sequences)

# Confirm conversion
print("✅ Data Type After Conversion:", type(sequences))


✅ Data Type After Conversion: <class 'numpy.ndarray'>


In [ ]:
from keras.utils import to_categorical

# First 24 words
print(sequences[:,:-1])

# last Word
print(sequences[:,-1])

X = sequences[:,:-1]
y = sequences[:,-1]
y = to_categorical(y, num_classes=vocabulary_size)

[[1314    1  767 ... 3694 3693  136]
 [   1  767  222 ... 3693  136 1315]
 [ 767  222    1 ...  136 1315    1]
 ...
 [1308   17  195 ...   14  341   57]
 [  17  195 3692 ...  341   57    2]
 [ 195 3692    3 ...   57    2 3702]]
[1315    1  114 ...    2 3702   16]


In [ ]:
X.shape[1]

25

In [ ]:
vocabulary_size

3703

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input

def create_model(vocabulary_size, seq_len):
    model = Sequential()

    # Explicit Input layer
    model.add(Input(shape=(seq_len,)))

    # Embedding Layer (No input_length needed)
    model.add(Embedding(input_dim=vocabulary_size, output_dim=25))

    # LSTM layers
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))

    # Fully connected layers
    model.add(Dense(150, activation='relu'))
    model.add(Dense(vocabulary_size, activation='softmax'))

    # Compile the model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    # Show model summary
    model.summary()

    return model

# Create the model
model = create_model(vocabulary_size, X.shape[1])


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 25, 25)              │          92,575 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_2 (LSTM)                        │ (None, 25, 150)             │         105,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 150)                 │          22,650 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 3703)                │         559,153 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 960,578 (3.66 MB)

 Trainable params: 960,578 (3.66 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X, y, batch_size=128, epochs=300, verbose=1)


Epoch 1/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.1113 - loss: 4.5525
Epoch 2/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.1140 - loss: 4.5320
Epoch 3/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.1170 - loss: 4.4716
Epoch 4/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.1219 - loss: 4.4101
Epoch 5/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.1204 - loss: 4.3683
Epoch 6/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1282 - loss: 4.3263
Epoch 7/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.1296 - loss: 4.2578
Epoch 8/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.1278 - loss: 4.2398
Epoch 9/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1404 - loss: 4.2059
Epoch 10/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1417 - loss: 4.1520
Epoch 11/300
129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.1382 - loss: 4.0931
Epoch 12/300
129/129 ━━━━━━━━━

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [ ]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    """
    Generates text based on the trained model.

    Parameters:
    - model: Trained LSTM model.
    - tokenizer: Fitted Keras Tokenizer.
    - seq_len: Length of input sequences (25 in our case).
    - seed_text: Initial text to start generation.
    - num_gen_words: Number of words to generate.

    Returns:
    - Generated text.
    """

    output_text = []
    input_text = seed_text

    for _ in range(num_gen_words):
        # Convert input text to sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]

        # Pad the sequence to match training sequence length
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')

        # Predict next word
        predicted_probs = model.predict(pad_encoded, verbose=0)[0]  # Get probability distribution
        predicted_word_index = np.argmax(predicted_probs)  # Get index of most probable word

        # Retrieve word from tokenizer
        predicted_word = tokenizer.index_word.get(predicted_word_index, "")

        # Append predicted word
        input_text += " " + predicted_word
        output_text.append(predicted_word)

    return " ".join(output_text)


In [ ]:
seed_text = ' '.join(text_sequences[0])
seed_text


'loomings the carpet bag the spouter inn the counterpane breakfast the street the chapel the pulpit the sermon a bosom friend nightgown biographical wheelbarrow nantucket chowder'

In [ ]:
seed_text = "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore,"

In [ ]:

num_words_to_generate = 20  # Adjust for longer/shorter text generation

generated_text = generate_text(model, tokenizer, X.shape[1], seed_text, num_words_to_generate)
print("📌 Generated Text:")
print(seed_text, generated_text)

📌 Generated Text:
Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, i thought he would sail to get into his pantaloons as soon as possible he complied a moving as does
